{% set data= load_setup_py_data() %}
package:
  name: ts-m2com
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - scipy
    - ts-conda-build =0.3
    - ts-simactuators
    - ts-xml
    - ts-idl {{ idl_version }}
    - ts-tcpip
    - ts-utils
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - py.test

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - scipy
    - pandas
    - ts-xml
    - ts-idl {{ idl_version }}
    - ts-simactuators
    - ts-tcpip
    - ts-utils
